### ISSUE TITLE
go install OSX El Capitain

### ISSUE THREAD

**Issue by john-dev** [salviati/go-qt5#28]
Hello,

im trying to get this repo running on OSX 10.10.x El Capitain..
Looks good until i run "go install" in the qt5 folder.

It says: 
github.com/salviati/go-qt5/qt5
# github.com/salviati/go-qt5/qt5
ld: library not found for -lgoqt5drv
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Any ideas?

**Comment by nbjahan** [comment]
@john-dev did you build the `goqtdrv5`?

**Comment by john-dev** [comment]
Yes i did with success, the dylib files have been written to /usr/lib.. (had to disable System Integrity Protection)

**Comment by nbjahan** [comment]
so if the dylibs are in /usr/lib/ you can do this:
`CGO_LDFLAGS="-L/usr/lib" go install`
or:
`CGO_LDFLAGS="-L$GOPATH/src/github.com/salviati/go-qt5/lib" go install`

**Comment by nbjahan** [comment]
Here is what I did to test this (I didn't install the c layer just built it)
```
$ brew link --force qt5
$ go get github.com/salviati/go-qt5
$ cd $GOPATH/src/github.com/salviati/go-qt5/make
$ lua make.lua
$ lua makelib.lua
$ cd $GOPATH/src/github.com/salviati/go-qt5/goqtdrv5
$ qmake "CONFIG+=release"
$ make
$ cd $GOPATH/src/github.com/salviati/go-qt5/qt5
$ CGO_LDFLAGS="-L$GOPATH/src/github.com/salviati/go-qt5/lib" go install
$ cd $GOPATH/src/github.com/salviati/go-qt5/examples
$ DYLD_LIBRARY_PATH=$GOPATH/src/github.com/salviati/go-qt5/lib go run minimal.go
```

**Comment by john-dev** [comment]
Thats just wonderful, thanks a lot - worked like a charm! :)

**Comment by john-dev** [comment]
Ok, i closed this issue a little bit too fast:

The go install worked fine for me!
No matter what example i run, i always get penic errors.

DYLD_LIBRARY_PATH=$GOPATH/src/github.com/salviati/go-qt5/lib go run minimal.go
0.1.1
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
panic(0x41de760, 0xc82000a2c0)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/salviati/go-qt5/qt5._cgoCheckPointer0(0x414ab60, 0x43b7460, 0x0, 0x0, 0x0, 0x40ff7a4)
	github.com/salviati/go-qt5/qt5/_obj/_cgo_gotypes.go:42 +0x4d
github.com/salviati/go-qt5/qt5._drv(0x1, 0x1, 0x43b7460, 0xc82000a2b8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/Severin/Documents/Atom/go/src/github.com/salviati/go-qt5/qt5/cdrv.go:93 +0x5d
github.com/salviati/go-qt5/qt5.(*app).AppMain(0x43b7460, 0x0)
	/Users/Severin/Documents/Atom/go/src/github.com/salviati/go-qt5/qt5/uiobjs.go:1893 +0xb4
github.com/salviati/go-qt5/qt5.Main(0x429e588, 0x1)
	/Users/Severin/Documents/Atom/go/src/github.com/salviati/go-qt5/qt5/ui.go:22 +0x38
main.main()
	/Users/Severin/Documents/Atom/go/src/github.com/salviati/go-qt5/examples/minimal.go:17 +0xf9
exit status 2

**Comment by nbjahan** [comment]
There are some new restrictions regarding cgo in go1.6+ :[more info](https://golang.org/cmd/cgo/#hdr-Passing_pointers) 

you can bypass them with this environment variable until the proper fix: `GODEBUG=cgocheck=0`

**Comment by john-dev** [comment]
Thanks, this worked for me.
